import _ from 'lodash';


_.assign(OnetimePass, {

  /**
   * @callback loginCB
   * @param {object} error
   */

  /**
   * Attempt a full token login
   * @param {string} token - generated by generateOTPToken
   * @param {loginCB} cb
   */
  loginWithToken (OTPToken, cb) {
    let loginRequest = {'oneTimePass.OTPToken': OTPToken};

    Accounts.callLoginMethod({
      methodArguments: [loginRequest],
      userCallback: cb
    });
  },

});
